name: Custom Github Pages Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.1.0

      - uses: actions/checkout@v2

      - name: Install and Build 🔧
        run: |
          pnpm i
          pnpm run export

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
          branch: gh-pages
